### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [Rellganss/belajarbersamapmb#1]
### Hi Darrell

Kodemu strukturnya kurang tepat dengan ketentuan nih, bisa dibaikin kayak gini yah
```html
<header>...</header>
<main>
 <div id="content">
  <section id="article">
   <article>...</article> 
   <article>...</article> 
   <article>...</article> 
  </section>
  <section id="form">
   <form></form>
  </section>
 </div>
 <aside>....</div>
</main>
<footer>...</footer>
```
Lalu kamu masih kekurangan elemen didalam `form` dan `aside` kamu ga masuk ke dalam `main` nih. Dibaikin lalu upload ulang direpository ini aja, kalau sudah komen dibawah Thanks!

**Comment by Rellganss** [comment]
sudah bang, mungkin bisa di cek ulang

**Comment by not-xygen** [comment]
### Halo Darrell

Oke good, sangat bagus. Submission Approved, Goodluck nanti CSS-nya!!
